### ISSUE TITLE
Porting to python3

### ISSUE THREAD

**Issue by jrvarma** [cscorley/send.py#1]
I have been a very happy user of `send.py` for many years now. Thanks a lot for making this available. After `offlineimap` moved to python 3, I am trying to eliminate dependence on python 2 completely. 

How hard would it be to port `send.py` to python 3?  If you think that it is only a question of changing some python 2 libraries to equivalent python 3 libraries, I could try doing so myself and submit a pull request. If you think it will take more effort, I will stick to python 2 for some more time.

**Comment by cscorley** [comment]
That's great to hear, glad to see you have gotten a lot of use out of this little tool.

I think if you'd like to try to port to Python 3, you should give it a shot!  I believe it should be mostly the same code, with just some following tweaks:

1. Imports for some packages likely need to change
2. There is some string/byte encoding that will likely need to be addressed

Just about every port I've seen for Python 2 ends up doing these things.  If you get stuck, just let me know!  I can also aim to do this over the holiday / new year if you don't end up trying it :)

**Comment by jrvarma** [comment]
These were the changes that I made to make `send.py` work in python 3
```
-from ConfigParser import ConfigParser
+from configparser import ConfigParser
-import urllib
+import urllib.request
+import urllib.parse
+import urllib.error
-    response = urllib.urlopen(oauth.request_url,
-                              urllib.urlencode(params)).read()
+    response = urllib.request.urlopen(
+        oauth.request_url,
+        urllib.parse.urlencode(params).encode("utf-8")).read()
-    auth_string = base64.b64encode(auth_string)
+    auth_string = base64.b64encode(auth_string.encode("utf-8")).decode("utf-8")
```
Perhaps `import urllib.error` is not needed but `2to3` suggested it and I was too lazy to check whether it is needed.

I am not submitting a proper pull request with a patch because my copy of `send.py` has some other changes that would make a patch file useless.

**Comment by cscorley** [comment]
Thanks!  I have merged this in.
